version: '3'

services:
  db:
    image: postgres
    environment:
        - POSTGRES_DB=cars_api
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=1234
  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: cars_api
    volumes:
      - .:/cars_api
    ports:
      - "8000:8000"
    depends_on:
      - "db"