# Generated by Django 3.1 on 2020-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
